# Generated by Django 2.2.6 on 2020-03-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_http',
            field=models.BooleanField(default=True, verbose_name='是否为站内地址'),
        ),
    ]
