# Generated by Django 2.2.6 on 2020-03-07 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200307_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='nav',
            name='icon',
            field=models.CharField(default='iconfont ic-navigation-notification menu-icon', max_length=100, verbose_name='图标'),
        ),
    ]
