# Generated by Django 2.2.6 on 2020-03-02 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(help_text='昵称', max_length=15, null=True, unique=True, verbose_name='昵称'),
        ),
    ]
