# Generated by Django 2.2.6 on 2020-03-17 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='title',
        ),
        migrations.AddField(
            model_name='articleimage',
            name='user',
            field=models.IntegerField(blank=True, null=True, verbose_name='上传图片的用户'),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='是否发布'),
        ),
        migrations.AlterField(
            model_name='article',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='作者'),
        ),
        migrations.AlterField(
            model_name='articlecollection',
            name='name',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='special',
            name='collect_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='收藏数量'),
        ),
        migrations.AlterField(
            model_name='special',
            name='follow_count',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='关注数量'),
        ),
        migrations.AlterField(
            model_name='special',
            name='name',
            field=models.CharField(max_length=150, verbose_name='标题'),
        ),
        migrations.AlterField(
            model_name='specialfocus',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='用户'),
        ),
    ]
